# Generated by Django 4.0.5 on 2023-01-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='data',
        ),
        migrations.AddField(
            model_name='notes',
            name='data',
            field=models.ManyToManyField(related_name='notesdata', to='services.createstudymaterialservice'),
        ),
    ]
