# Generated by Django 4.0.5 on 2023-01-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_notes_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='data',
            field=models.ManyToManyField(blank=True, related_name='notesdata', to='services.createstudymaterialservice'),
        ),
    ]
