# Generated by Django 4.0.5 on 2022-09-17 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=225, null=True)),
                ('document', models.ManyToManyField(to='services.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.RemoveField(
            model_name='notes',
            name='data',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.DeleteModel(
            name='CreateStudyMaterialService',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
