# Generated by Django 4.0.5 on 2022-08-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_notes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
