# Generated by Django 4.0.5 on 2022-08-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_createstudymaterialservice_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
