# Generated by Django 4.0.5 on 2022-08-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_notes_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstudymaterialservice',
            name='query',
            field=models.CharField(blank=True, default=' ', max_length=1000),
        ),
    ]
