# Generated by Django 4.0.5 on 2022-08-22 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_notes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notesdata', to='services.createstudymaterialservice'),
        ),
    ]
